booking:
  database_url: "/homestaysofhimalaya/dev-integration/booking/database_url"
  redis_url: "/homestaysofhimalaya/dev-integration/booking/redis_url"
payments:
  database_url: "/homestaysofhimalaya/dev-integration/payments/database_url"
  redis_url: "/homestaysofhimalaya/dev-integration/payments/redis_url"
