booking:
  database_url: "/homestaysofhimalaya/dev-production/booking/database_url"
  redis_url: "/homestaysofhimalaya/dev-production/booking/redis_url"

users:
  database_url: "/homestaysofhimalaya/dev-production/users/database_url"
  redis_url: "/homestaysofhimalaya/dev-production/users/redis_url"

