booking:
  database_url: "/homestaysofhimalaya/dev-integration/booking/database_url"
  redis_url: "/homestaysofhimalaya/dev-integration/booking/redis_url"

users:
  database_url: "/homestaysofhimalaya/dev-integration/users/database_url"
  redis_url: "/homestaysofhimalaya/dev-integration/users/redis_url"

