openapi: 3.0.0
info:
  title: Homestays API
  version: 1.0.0
servers:
  - url: /
paths:
  /homestays:
    get:
      summary: List available homestays
      security:
        - ApiKeyAuth: []
        - OAuth2ClientCredentials: []
      responses:
        '200':
          description: A JSON array of homestays
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Homestay'
  /bookings:
    get:
      summary: Booking service status
      security:
        - ApiKeyAuth: []
        - OAuth2ClientCredentials: []
      responses:
        '200':
          description: Booking service root response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceStatus'
  /users:
    get:
      summary: User service status
      security:
        - ApiKeyAuth: []
        - OAuth2ClientCredentials: []
      responses:
        '200':
          description: User service root response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceStatus'
  /payments:
    get:
      summary: Payment service status
      security:
        - ApiKeyAuth: []
        - OAuth2ClientCredentials: []
      responses:
        '200':
          description: Payment service root response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceStatus'
components:
  schemas:
    Homestay:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        location:
          type: string
    ServiceStatus:
      type: object
      properties:
        service:
          type: string
        message:
          type: string
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    OAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://example.com/oauth/token
          scopes:
            read: Read access to homestays
security:
  - ApiKeyAuth: []
  - OAuth2ClientCredentials: []
