openapi: 3.0.0
info:
  title: Homestays API
  version: 1.0.0
servers:
  - url: /
paths:
  /homestays:
    get:
      summary: Search available homestays
      parameters:
        - in: query
          name: min_price
          schema:
            type: number
          description: Minimum nightly price
        - in: query
          name: max_price
          schema:
            type: number
          description: Maximum nightly price
        - in: query
          name: amenities
          schema:
            type: array
            items:
              type: string
          style: form
          explode: false
          description: Comma separated list of required amenities
        - in: query
          name: start_date
          schema:
            type: string
            format: date
          description: Start of availability window
        - in: query
          name: end_date
          schema:
            type: string
            format: date
          description: End of availability window
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number for pagination
        - in: query
          name: size
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Page size for pagination
      security:
        - ApiKeyAuth: []
        - OAuth2ClientCredentials: []
      responses:
        '200':
          description: A paginated list of homestays
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Homestay'
                  page:
                    type: integer
                  size:
                    type: integer
  /bookings:
    get:
      summary: Booking service status
      security:
        - ApiKeyAuth: []
        - OAuth2ClientCredentials: []
      responses:
        '200':
          description: Booking service root response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceStatus'
  /bookings/itinerary/{booking_id}:
    get:
      summary: Retrieve itinerary for a booking
      parameters:
        - in: path
          name: booking_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Itinerary for the booking
          content:
            application/json:
              schema:
                type: object
                properties:
                  booking_id:
                    type: integer
                  itinerary:
                    type: array
                    items:
                      type: object
                      properties:
                        day:
                          type: integer
                        activity:
                          type: string
  /bookings/history/{user_id}:
    get:
      summary: List booking history for a user
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User booking history
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                  bookings:
                    type: array
                    items:
                      type: object
                      properties:
                        booking_id:
                          type: integer
                        status:
                          type: string
  /users:
    get:
      summary: User service status
      security:
        - ApiKeyAuth: []
        - OAuth2ClientCredentials: []
      responses:
        '200':
          description: User service root response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceStatus'
  /payments:
    get:
      summary: Payment service status
      security:
        - ApiKeyAuth: []
        - OAuth2ClientCredentials: []
      responses:
        '200':
          description: Payment service root response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceStatus'
  /payments/methods:
    get:
      summary: List available payment methods
      responses:
        '200':
          description: Available payment methods
          content:
            application/json:
              schema:
                type: object
                properties:
                  methods:
                    type: array
                    items:
                      type: string
  /payments/pay:
    post:
      summary: Process a payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                method:
                  type: string
                promo_code:
                  type: string
      responses:
        '200':
          description: Payment processing result
          content:
            application/json:
              schema:
                type: object
                properties:
                  method:
                    type: string
                  amount_charged:
                    type: number
  /packages:
    get:
      summary: List available travel packages
      responses:
        '200':
          description: Travel packages
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
  /packages/recommendations:
    get:
      summary: Recommended packages
      parameters:
        - in: query
          name: user_id
          schema:
            type: integer
          description: User identifier for personalized recommendations
      responses:
        '200':
          description: Recommended packages
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                  recommendations:
                    type: array
                    items:
                      type: integer
components:
  schemas:
    Homestay:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        location:
          type: string
    ServiceStatus:
      type: object
      properties:
        service:
          type: string
        message:
          type: string
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    OAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://example.com/oauth/token
          scopes:
            read: Read access to homestays
security:
  - ApiKeyAuth: []
  - OAuth2ClientCredentials: []
