name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - run: echo 'Deploying to dev'
        env:
          API_KEY: ${{ secrets.DEV_API_KEY }}

  deploy_test:
    runs-on: ubuntu-latest
    needs: deploy_dev
    environment: test
    steps:
      - uses: actions/checkout@v3
      - run: echo 'Deploying to test'
        env:
          API_KEY: ${{ secrets.TEST_API_KEY }}

  deploy_qa:
    runs-on: ubuntu-latest
    needs: deploy_test
    environment: qa
    steps:
      - uses: actions/checkout@v3
      - run: echo 'Deploying to qa'
        env:
          API_KEY: ${{ secrets.QA_API_KEY }}

  deploy_qa_staging:
    runs-on: ubuntu-latest
    needs: deploy_qa
    environment: qa-staging
    steps:
      - uses: actions/checkout@v3
      - run: echo 'Deploying to qa-staging'
        env:
          API_KEY: ${{ secrets.QA_STAGING_API_KEY }}

  deploy_production:
    runs-on: ubuntu-latest
    needs: deploy_qa_staging
    environment:
      name: production
    steps:
      - uses: actions/checkout@v3
      - run: echo 'Deploying to production'
        env:
          API_KEY: ${{ secrets.PRODUCTION_API_KEY }}
